import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname, isAbsolute } from 'node:path';
import { z } from 'zod';
/**
 * Engine configuration.
 *
 * Nothing operational is compiled in. Values resolve in this order, last wins:
 *
 *   1. the defaults in this schema
 *   2. `config/default.json` shipped with the engine
 *   3. the file at `HERALD_CONFIG` (or `./herald.config.json`)
 *   4. environment variables
 *
 * A missing or malformed config fails at boot with the offending path named,
 * rather than surfacing as a mystery at 3am during a crawl.
 */
const SourceAuthSchema = z.object({
    type: z.enum(['none', 'bearer', 'header', 'basic']).default('none'),
    /** Read from an env var so tokens never sit in the config file. */
    tokenEnv: z.string().optional(),
    headerName: z.string().optional(),
    usernameEnv: z.string().optional(),
    passwordEnv: z.string().optional(),
});
/**
 * Maps fields of an arbitrary JSON payload onto the normalized posting shape.
 * Each value is a dotted path into the source record; `[]` walks an array.
 */
const FieldMapSchema = z.object({
    id: z.string().optional(),
    title: z.string(),
    company: z.string().optional(),
    location: z.string().optional(),
    remote: z.string().optional(),
    pay: z.string().optional(),
    payMin: z.string().optional(),
    payMax: z.string().optional(),
    payCurrency: z.string().optional(),
    url: z.string().optional(),
    applyUrl: z.string().optional(),
    postedAt: z.string().optional(),
    description: z.string().optional(),
});
const SourceSchema = z.object({
    /** Stable identifier shown in the UI as the "Source" meta value. */
    id: z.string().min(1),
    /** Display name; defaults to a title-cased id. */
    name: z.string().optional(),
    /** Which adapter reads this source. */
    adapter: z.enum(['greenhouse', 'lever', 'ashby', 'workday', 'json', 'command']),
    enabled: z.boolean().default(true),
    /**
     * Adapter-specific settings — board slugs, tenant hosts, an endpoint URL,
     * or the argv of an aggregator CLI. Validated by the adapter itself.
     */
    options: z.record(z.string(), z.unknown()).default({}),
    auth: SourceAuthSchema.prefault({}),
    /** Only needed by the `json` adapter; ignored elsewhere. */
    fieldMap: FieldMapSchema.optional(),
    /** Requests per minute this source tolerates. */
    rateLimitPerMinute: z.number().int().positive().default(60),
    /** Company name to stamp on postings from single-company boards. */
    company: z.string().optional(),
    /**
     * When several sources carry the same posting, the highest wins and the
     * others collapse into it. ATS originals should outrank aggregators.
     */
    priority: z.number().int().default(0),
});
const ConfigSchema = z.object({
    server: z.object({
        host: z.string().default('0.0.0.0'),
        port: z.number().int().min(1).max(65535).default(8787),
        /** Origins allowed to call the API. The desktop app adds its own at runtime. */
        corsOrigins: z.array(z.string()).default([]),
        /** Public URL the phone reaches, used to build the pairing QR payload. */
        publicUrl: z.string().nullable().default(null),
    }).prefault({}),
    auth: z.object({
        /**
         * Bearer token. Generated by `npm run init` and written to the config file;
         * `HERALD_TOKEN` overrides it. The engine refuses to start without one.
         */
        token: z.string().nullable().default(null),
    }).prefault({}),
    storage: z.object({
        /** Directory for the SQLite file, resume, and confirmation screenshots. */
        dataDir: z.string().default('./data'),
        databaseFile: z.string().default('herald.sqlite'),
    }).prefault({}),
    schedule: z.object({
        /** Cron for the ingest→score pipeline. Hourly on the hour by default. */
        crawlCron: z.string().default('0 * * * *'),
        /** Cron for the mailbox reply sweep. */
        trackCron: z.string().default('*/30 * * * *'),
        /** Run a crawl immediately at boot instead of waiting for the first tick. */
        crawlOnBoot: z.boolean().default(false),
        /** Skip the daily scan entirely — useful while developing. */
        enabled: z.boolean().default(true),
    }).prefault({}),
    llm: z.object({
        provider: z.literal('anthropic').default('anthropic'),
        /** Read from `ANTHROPIC_API_KEY`; never stored in the config file. */
        apiKeyEnv: z.string().default('ANTHROPIC_API_KEY'),
        /** Scoring model. Cheap and fast matters more than depth here. */
        scoreModel: z.string().default('claude-sonnet-5'),
        /** Cover letters and resume parsing get the stronger model. */
        writeModel: z.string().default('claude-sonnet-5'),
        maxOutputTokens: z.number().int().positive().default(2048),
        /** Concurrent scoring calls. Raise only if your rate limit allows. */
        concurrency: z.number().int().positive().default(4),
        /** Directory of prompt templates, so wording changes need no rebuild. */
        promptDir: z.string().default('./config/prompts'),
        /** Hard ceiling on scoring calls per crawl, as a cost guard. */
        maxScoresPerCrawl: z.number().int().positive().default(400),
    }).prefault({}),
    matching: z.object({
        /** Below this, a posting never reaches the Matches feed at all. */
        feedFloor: z.number().int().min(0).max(100).default(60),
        /** How far back a crawl looks on its first ever run. */
        initialLookbackHours: z.number().int().positive().default(48),
        /** Postings older than this are dropped at ingest. */
        maxPostingAgeDays: z.number().int().positive().default(30),
    }).prefault({}),
    apply: z.object({
        /** Master switch for the Playwright submit step. */
        enabled: z.boolean().default(true),
        headless: z.boolean().default(true),
        timeoutMs: z.number().int().positive().default(60_000),
        /** Hosts Herald will never automate; these route to `needs_you`. */
        manualOnlyHosts: z.array(z.string()).default(['linkedin.com', 'www.linkedin.com']),
        /** Store a screenshot of every confirmation page. */
        screenshotConfirmations: z.boolean().default(true),
        /** Path to the form field-mapping rules. */
        fieldRulesFile: z.string().default('./config/field-rules.json'),
    }).prefault({}),
    notifications: z.object({
        enabled: z.boolean().default(true),
        provider: z.enum(['fcm', 'none']).default('fcm'),
        /** Path to the Firebase service-account JSON. Absent = push disabled. */
        fcmServiceAccountFile: z.string().nullable().default(null),
        /** Overrides the project id from the service account when set. */
        fcmProjectId: z.string().nullable().default(null),
    }).prefault({}),
    tracking: z.object({
        /** Mailbox sweep that classifies replies into interview/rejected. */
        enabled: z.boolean().default(false),
        provider: z.enum(['gmail', 'none']).default('none'),
        gmailCredentialsFile: z.string().nullable().default(null),
        /** Only messages under this label are read. Keep the scope narrow. */
        gmailLabel: z.string().default('Herald'),
    }).prefault({}),
    releases: z.object({
        /** Feed the in-app updater and What's new screen read. */
        indexUrl: z.string().nullable().default(null),
        /** Cache lifetime for the proxied feed. */
        cacheMinutes: z.number().int().positive().default(30),
    }).prefault({}),
    sources: z.array(SourceSchema).default([]),
    logging: z.object({
        level: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace']).default('info'),
    }).prefault({}),
});
/** Environment overrides. Keys are dotted config paths. */
const ENV_MAP = {
    HERALD_HOST: 'server.host',
    HERALD_PORT: 'server.port',
    HERALD_PUBLIC_URL: 'server.publicUrl',
    HERALD_TOKEN: 'auth.token',
    HERALD_DATA_DIR: 'storage.dataDir',
    HERALD_CRAWL_CRON: 'schedule.crawlCron',
    HERALD_TRACK_CRON: 'schedule.trackCron',
    HERALD_CRAWL_ON_BOOT: 'schedule.crawlOnBoot',
    HERALD_SCHEDULE_ENABLED: 'schedule.enabled',
    HERALD_SCORE_MODEL: 'llm.scoreModel',
    HERALD_WRITE_MODEL: 'llm.writeModel',
    HERALD_LLM_CONCURRENCY: 'llm.concurrency',
    HERALD_MAX_SCORES_PER_CRAWL: 'llm.maxScoresPerCrawl',
    HERALD_FEED_FLOOR: 'matching.feedFloor',
    HERALD_APPLY_ENABLED: 'apply.enabled',
    HERALD_APPLY_HEADLESS: 'apply.headless',
    HERALD_NOTIFICATIONS_ENABLED: 'notifications.enabled',
    HERALD_FCM_SERVICE_ACCOUNT: 'notifications.fcmServiceAccountFile',
    HERALD_FCM_PROJECT_ID: 'notifications.fcmProjectId',
    HERALD_RELEASES_INDEX_URL: 'releases.indexUrl',
    HERALD_LOG_LEVEL: 'logging.level',
};
export function loadConfig(explicitPath) {
    const builtinDefaults = readJsonIfPresent(resolve(packageRoot(), 'config/default.json'));
    const configPath = explicitPath
        ?? process.env.HERALD_CONFIG
        ?? firstExisting([resolve(process.cwd(), 'herald.config.json'), resolve(packageRoot(), 'herald.config.json')]);
    const fileConfig = configPath ? readJsonOrThrow(configPath) : {};
    let merged = deepMerge(deepMerge({}, builtinDefaults), fileConfig);
    merged = applyEnv(merged);
    const parsed = ConfigSchema.safeParse(merged);
    if (!parsed.success) {
        const issues = parsed.error.issues
            .map((i) => `  ${i.path.join('.') || '(root)'}: ${i.message}`)
            .join('\n');
        throw new Error(`Invalid Herald config${configPath ? ` (${configPath})` : ''}:\n${issues}`);
    }
    const config = parsed.data;
    // Relative paths resolve against the config file's directory when there is
    // one, so a config can be moved with its data dir and keep working.
    const base = configPath ? dirname(configPath) : process.cwd();
    const abs = (p) => (isAbsolute(p) ? p : resolve(base, p));
    const dataDir = abs(config.storage.dataDir);
    return {
        ...config,
        configPath: configPath ?? null,
        paths: {
            dataDir,
            database: resolve(dataDir, config.storage.databaseFile),
            resumes: resolve(dataDir, 'resumes'),
            screenshots: resolve(dataDir, 'screenshots'),
            promptDir: abs(config.llm.promptDir),
            fieldRules: abs(config.apply.fieldRulesFile),
        },
    };
}
/** Resolves a source's secret from the environment, never from the config file. */
export function resolveSourceAuth(source) {
    const { auth } = source;
    switch (auth.type) {
        case 'bearer': {
            const token = auth.tokenEnv ? process.env[auth.tokenEnv] : undefined;
            return token ? { Authorization: `Bearer ${token}` } : {};
        }
        case 'header': {
            const token = auth.tokenEnv ? process.env[auth.tokenEnv] : undefined;
            return token && auth.headerName ? { [auth.headerName]: token } : {};
        }
        case 'basic': {
            const user = auth.usernameEnv ? process.env[auth.usernameEnv] : undefined;
            const pass = auth.passwordEnv ? process.env[auth.passwordEnv] : undefined;
            if (!user || !pass)
                return {};
            return { Authorization: `Basic ${Buffer.from(`${user}:${pass}`).toString('base64')}` };
        }
        default:
            return {};
    }
}
// ── helpers ────────────────────────────────────────────────────────────────
function packageRoot() {
    // dist/config.js and src/config.ts both sit one level under the package root.
    return resolve(dirname(new URL(import.meta.url).pathname), '..');
}
function firstExisting(candidates) {
    return candidates.find((c) => existsSync(c));
}
function readJsonIfPresent(path) {
    return existsSync(path) ? readJsonOrThrow(path) : {};
}
function readJsonOrThrow(path) {
    try {
        return JSON.parse(readFileSync(path, 'utf8'));
    }
    catch (cause) {
        throw new Error(`Could not read config at ${path}: ${cause.message}`);
    }
}
function applyEnv(target) {
    const out = target;
    for (const [envKey, path] of Object.entries(ENV_MAP)) {
        const raw = process.env[envKey];
        if (raw === undefined || raw === '')
            continue;
        setPath(out, path, coerce(raw));
    }
    return out;
}
/** Turns "8787" into 8787 and "true" into true so env strings satisfy the schema. */
function coerce(raw) {
    if (raw === 'true')
        return true;
    if (raw === 'false')
        return false;
    if (raw === 'null')
        return null;
    if (/^-?\d+$/.test(raw))
        return Number(raw);
    return raw;
}
function setPath(target, path, value) {
    const keys = path.split('.');
    let node = target;
    for (const key of keys.slice(0, -1)) {
        if (typeof node[key] !== 'object' || node[key] === null)
            node[key] = {};
        node = node[key];
    }
    node[keys[keys.length - 1]] = value;
}
function deepMerge(base, patch) {
    const out = { ...base };
    for (const [key, value] of Object.entries(patch)) {
        const existing = out[key];
        if (isPlainObject(existing) && isPlainObject(value)) {
            out[key] = deepMerge(existing, value);
        }
        else {
            // Arrays replace rather than concatenate: a user listing three sources
            // means exactly three, not three plus whatever shipped by default.
            out[key] = value;
        }
    }
    return out;
}
function isPlainObject(value) {
    return typeof value === 'object' && value !== null && !Array.isArray(value);
}
//# sourceMappingURL=config.js.map