#!/usr/bin/env node
/**
 * Propagates the single source of truth for the version — the root
 * package.json — into the places the app builds read it from.
 *
 * The Android `versionCode` is derived with `androidVersionCode` from
 * @herald/core so CI, the in-app updater and the build all agree on what a tag
 * means. Run it after bumping the version and before any build:
 *
 *   node scripts/sync-version.mjs [version]
 *
 * With no argument it uses whatever the root package.json says.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { androidVersionCode, formatVersion, parseVersion } from '../packages/core/dist/index.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function writeJson(path, value) {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

const rootPkgPath = resolve(root, 'package.json');
const rootPkg = readJson(rootPkgPath);

const version = formatVersion(process.argv[2] ?? rootPkg.version);
if (!parseVersion(version)) {
  console.error(`Not a semantic version: ${version}`);
  process.exit(1);
}

const versionCode = androidVersionCode(version);

// Root and every workspace package share one version number, so a tag names
// exactly one build of everything.
const packages = [
  rootPkgPath,
  resolve(root, 'packages/core/package.json'),
  resolve(root, 'services/engine/package.json'),
  resolve(root, 'apps/android/package.json'),
  resolve(root, 'apps/desktop/package.json'),
];

for (const path of packages) {
  try {
    const pkg = readJson(path);
    if (pkg.version === version) continue;
    pkg.version = version;
    writeJson(path, pkg);
    console.log(`  ${path.replace(`${root}/`, '')} -> ${version}`);
  } catch (cause) {
    if (cause.code !== 'ENOENT') throw cause;
  }
}

// app.config.ts reads this rather than recomputing the version code, so the
// formula lives in exactly one place.
const generated = resolve(root, 'apps/android/version.generated.json');
writeJson(generated, {
  _comment: 'Generated by scripts/sync-version.mjs. Do not edit by hand.',
  version,
  androidVersionCode: versionCode,
});
console.log(`  apps/android/version.generated.json -> ${version} (versionCode ${versionCode})`);

// Tauri reads its version from here.
const tauriConfPath = resolve(root, 'apps/desktop/src-tauri/tauri.conf.json');
try {
  const conf = readJson(tauriConfPath);
  if (conf.version !== version) {
    conf.version = version;
    writeJson(tauriConfPath, conf);
    console.log(`  apps/desktop/src-tauri/tauri.conf.json -> ${version}`);
  }
} catch (cause) {
  if (cause.code !== 'ENOENT') throw cause;
}

console.log(`\nVersion ${version} · Android versionCode ${versionCode}`);
